Produce better error messages when invalid paths are passed to scripts.
* morph_check and raw_data_check now produce something like
    ERROR: Invalid data path: <the bad path>
  instead of producing confusing errors.

Change-Id: Ia3265b61b7342263de5b99a68ac24b51fd7b592e